### PR TITLE
failing because of fmt check

### PR DESCRIPTION
**Pull request by bmtoml**

### CODE REVIEW

**Comment by bmtoml** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
exit status 3: running "terraform fmt -check=true -diff=true -write=false" in "/home/atlantis/.atlantis/repos/bmtoml/atlaaaaaaantis/23/default": 
foo.tf
--- old/foo.tf
+++ new/foo.tf
@@ -1,10 +1,10 @@
 resource "aws_vpc" "boop" {
-  count = 1
+  count      = 1
   cidr_block = "192.127.127.0/24"
 }
 
 resource "aws_vpc" "boop2" {
-  count = 1
+  count      = 1
   cidr_block = "192.127.128.0/24"
 }
 


```
</details>

**Comment by bmkrra** [comment]
atlantis apply

**Comment by bmtoml** [comment]
Ran Apply for 0 projects:

**Comment by bmtoml** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_vpc.boop[0] will be created
+ resource "aws_vpc" "boop" {
      + arn                              = (known after apply)
      + assign_generated_ipv6_cidr_block = false
      + cidr_block                       = "192.127.127.0/24"
      + default_network_acl_id           = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_group_id        = (known after apply)
      + dhcp_options_id                  = (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
      + enable_dns_hostnames             = (known after apply)
      + enable_dns_support               = true
      + id                               = (known after apply)
      + instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      + main_route_table_id              = (known after apply)
      + owner_id                         = (known after apply)
    }

  # aws_vpc.boop2[0] will be created
+ resource "aws_vpc" "boop2" {
      + arn                              = (known after apply)
      + assign_generated_ipv6_cidr_block = false
      + cidr_block                       = "192.127.128.0/24"
      + default_network_acl_id           = (known after apply)
      + default_route_table_id           = (known after apply)
      + default_security_group_id        = (known after apply)
      + dhcp_options_id                  = (known after apply)
      + enable_classiclink               = (known after apply)
      + enable_classiclink_dns_support   = (known after apply)
      + enable_dns_hostnames             = (known after apply)
      + enable_dns_support               = true
      + id                               = (known after apply)
      + instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      + main_route_table_id              = (known after apply)
      + owner_id                         = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.247.12.82/lock?id=bmtoml%252Fatlaaaaaaantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by bmkrra** [comment]
atlantis apply

**Comment by bmtoml** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be approved before running apply.

**Comment by bmkrra** [comment]
atlantis apply

**Comment by bmtoml** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false -no-color \"/home/atlantis/.atlantis/repos/bmtoml/atlaaaaaaantis/23/default/default.tfplan\"" in "/home/atlantis/.atlantis/repos/bmtoml/atlaaaaaaantis/23/default": exit status 1
aws_vpc.boop2[0]: Creating...
aws_vpc.boop[0]: Creating...
aws_vpc.boop2[0]: Creation complete after 1s [id=vpc-010b496c1a4a86079]

Error: InvalidVpcID.NotFound: The vpc ID 'vpc-0949bd484f54943aa' does not exist
	status code: 400, request id: 3d6e36ef-cbd5-4b6b-9de6-cb21256f4f8c

  on foo.tf line 1, in resource "aws_vpc" "boop":
   1: resource "aws_vpc" "boop" {



```

**Comment by bmtoml** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_vpc.boop[0] is tainted, so must be replaced
-/+ resource "aws_vpc" "boop" {
      ~ arn                              = "arn:aws:ec2:eu-west-1:259016875510:vpc/vpc-0949bd484f54943aa" -> (known after apply)
        assign_generated_ipv6_cidr_block = false
        cidr_block                       = "192.127.127.0/24"
      ~ default_network_acl_id           = "acl-03d12699ab6815a7f" -> (known after apply)
      ~ default_route_table_id           = "rtb-0718dbab400689daa" -> (known after apply)
      ~ default_security_group_id        = "sg-03a5c6b0c41779c65" -> (known after apply)
      ~ dhcp_options_id                  = "dopt-9a4edffc" -> (known after apply)
      ~ enable_classiclink               = false -> (known after apply)
      ~ enable_classiclink_dns_support   = false -> (known after apply)
      ~ enable_dns_hostnames             = false -> (known after apply)
        enable_dns_support               = true
      ~ id                               = "vpc-0949bd484f54943aa" -> (known after apply)
        instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      ~ main_route_table_id              = "rtb-0718dbab400689daa" -> (known after apply)
      ~ owner_id                         = "259016875510" -> (known after apply)
      - tags                             = {} -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.247.12.82/lock?id=bmtoml%252Fatlaaaaaaantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by bmtoml** [comment]
atlantis plan

**Comment by bmtoml** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_vpc.boop[0] is tainted, so must be replaced
-/+ resource "aws_vpc" "boop" {
      ~ arn                              = "arn:aws:ec2:eu-west-1:259016875510:vpc/vpc-0949bd484f54943aa" -> (known after apply)
        assign_generated_ipv6_cidr_block = false
        cidr_block                       = "192.127.127.0/24"
      ~ default_network_acl_id           = "acl-03d12699ab6815a7f" -> (known after apply)
      ~ default_route_table_id           = "rtb-0718dbab400689daa" -> (known after apply)
      ~ default_security_group_id        = "sg-03a5c6b0c41779c65" -> (known after apply)
      ~ dhcp_options_id                  = "dopt-9a4edffc" -> (known after apply)
      ~ enable_classiclink               = false -> (known after apply)
      ~ enable_classiclink_dns_support   = false -> (known after apply)
      ~ enable_dns_hostnames             = false -> (known after apply)
        enable_dns_support               = true
      ~ id                               = "vpc-0949bd484f54943aa" -> (known after apply)
        instance_tenancy                 = "default"
      + ipv6_association_id              = (known after apply)
      + ipv6_cidr_block                  = (known after apply)
      ~ main_route_table_id              = "rtb-0718dbab400689daa" -> (known after apply)
      ~ owner_id                         = "259016875510" -> (known after apply)
      - tags                             = {} -> null
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.247.12.82/lock?id=bmtoml%252Fatlaaaaaaantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by bmtoml** [comment]
atlantis apply

**Comment by bmtoml** [comment]
Ran Apply for dir: `.` workspace: `default`

**Apply Failed**: Pull request must be mergeable before running apply.

**Comment by bmtoml** [comment]
atlantis apply

**Comment by bmtoml** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_vpc.boop[0]: Destroying... [id=vpc-0949bd484f54943aa]
aws_vpc.boop[0]: Destruction complete after 0s
aws_vpc.boop[0]: Creating...
aws_vpc.boop[0]: Creation complete after 1s [id=vpc-0c0075af7e35ea01c]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.

```

**Comment by bmtoml** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by bmtoml** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
