### PR TITLE
Feature/a

### PR DESCRIPTION
**Pull request by bmtoml**

### CODE REVIEW

**Comment by bmtoml** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # aws_vpc.johnholm[0] will be destroyed
- resource "aws_vpc" "johnholm" {
      - arn                              = "arn:aws:ec2:eu-west-1:259016875510:vpc/vpc-04b1e0b32ce390019" -> null
      - assign_generated_ipv6_cidr_block = false -> null
      - cidr_block                       = "192.127.129.0/24" -> null
      - default_network_acl_id           = "acl-042c40557c5b8375b" -> null
      - default_route_table_id           = "rtb-0917fa2116216c5ff" -> null
      - default_security_group_id        = "sg-07dacc20bdb86a99c" -> null
      - dhcp_options_id                  = "dopt-9a4edffc" -> null
      - enable_classiclink               = false -> null
      - enable_classiclink_dns_support   = false -> null
      - enable_dns_hostnames             = false -> null
      - enable_dns_support               = true -> null
      - id                               = "vpc-04b1e0b32ce390019" -> null
      - instance_tenancy                 = "default" -> null
      - main_route_table_id              = "rtb-0917fa2116216c5ff" -> null
      - owner_id                         = "259016875510" -> null
      - tags                             = {} -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://34.247.12.82/lock?id=bmtoml%252Fatlaaaaaaantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by bmkrra** [comment]
atlantis apply

**Comment by bmtoml** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
aws_vpc.johnholm[0]: Destroying... [id=vpc-04b1e0b32ce390019]
aws_vpc.johnholm[0]: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.

```

**Comment by bmtoml** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by bmtoml** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by bmkrra** [comment]
atlantis destroy

**Comment by bmtoml** [comment]
```
Error: unknown command "destroy".
Run 'atlantis --help' for usage.
```

**Comment by bmkrra** [comment]
atlantis --help

**Comment by bmtoml** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan   Runs 'terraform plan' for the changes in this pull request.
         To plan a specific project, use the -d, -w and -p flags.
  apply  Runs 'terraform apply' on all unapplied plans from this pull request.
         To only apply a specific plan, use the -d, -w and -p flags.
  help   View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by bmkrra** [comment]
atlantis plan

**Comment by bmtoml** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
